export const TYPE_ACTION = {
	PRODUCT: {
		GET_ALL_PRODUCT: 'GET_ALL_PRODUCT',
		DELETE_PRODUCT: 'DELETE_PRODUCT',
		ADD_PRODUCT: 'ADD_PRODUCT',
		EDIT_PRODUCT: 'EDIT_PRODUCT',
	},
	USER: {
		GET_ALL_USER: 'GET_ALL_USER',
		ADD_USER: 'ADD_USER',
		DELETE_USER: 'DELETE_USER',
		EDIT_USER: 'EDIT_USER',
		LOGIN: 'LOGIN',
		LOGOUT: 'LOGOUT',
	},
	CART: {
		GET_ALL_CART: 'GET_ALL_CART',
		DELETE_CART: 'DELETE_CART',
		ADD_CART: 'ADD_CART',
		EDIT_CART: 'EDIT_CART',
	},
	ADMIN: {
		LOGIN: 'LOGIN',
		LOGOUT: 'LOGOUT',
	},
	CATEGORY: {
		GET_LIST: 'GET_CATEGORY',
		DELETE_CATEGORY: 'DELETE_CATEGORY',
		POST_CATEGORY: 'POST_CATEGORY',
		PUT_CATEGORY: 'PUT_CATEGORY',
	},
};
